### ISSUE TITLE
Provide a fix

### ISSUE THREAD

**Issue by xperiandri** [TheAlmightyBob/AsyncVoidAnalyzer#2]

**Comment by TheAlmightyBob** [comment]
Any particular fix you're looking for?

I actually wrote a code fix provider for this, but I didn't push the change because I'm not sure it's a good idea for something like this. Depending on the context, the right fix might be to switch to "async task" or to add exception handling. If the latter, the particulars of how exceptions should be handled will vary by application. Providing a code "fix" that silently swallowed exceptions would be doing more harm than good.

The provider I wrote basically just wrapped everything in a try/catch where the catch contained a big "TODO!!" (I was even thinking of making it not compile so that the developer couldn't just ignore it). But at that point I'm not sure it's providing any real value to you... you're still going to have to do some thinking and typing, and Visual Studio already has the "surround with try/catch" snippet built-in.

Point being: I'm open to suggestions as to what a code fix provider should do to help with this. :)

**Comment by xperiandri** [comment]
Well any way you need to surround this call with try-catch.
Why not to provide a fix for this?
It can have 2 options:
- surround call
- surround whole method body

**Comment by TheAlmightyBob** [comment]
Well, if the desired fix is to convert from "async void" to "async task," then you _don't_ need to add a try-catch.

If you _do_ want to fix it by surrounding the logic with try-catch (and you don't want to just make that change manually yourself), then Visual Studio already has that feature built-in. So the question is what value a code fix version would be providing...?

I would _guess_ that one of the remaining benefits to a code fix would be the ability to apply it batch-style across a document/project/solution. However, that gets back to my concern about potentially doing more harm than good, since the developer should still review the code, add appropriate exception handling logic, etc. In other words, even if the fix provided multiple options (which I had considered), those options would still be incomplete... so applying a batch fix could just wind up _hiding_ the problem without actually fixing it...

Again, I'm quite open to feedback/ideas on this, I just can't think of a way for a fix to be both useful and safe...
